a = input('Digite algo:')
print('O tipo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('Só tem letras?', a.isalpha())
print('Só tem numeros?', a.isnumeric())
print ('Possui letras e numeros?', a.isalnum())
print('esta em maiusculas?', a.isupper())
print('Esta em minusculas', a.islower())
print('Está capitalizada?', a.istitle())
